import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import LoadingWrapper from "@/src/loadingFallback";
import ErrorWrapper from "@/src/error/wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ErrorWrapper>
          <LoadingWrapper>{children}</LoadingWrapper>
        </ErrorWrapper>
      </body>
    </html>
  );
}
