import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import LoadingProvider from '@/src/loading/suspense';
import Header from '@/src/header.tsx/component';
import UidContextProvider from '@/src/user/provider';
import ErrorContextProvider from '@/src/error/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <UidContextProvider>
          <ErrorContextProvider>
            <Header></Header>
            <LoadingProvider>{children}</LoadingProvider>
          </ErrorContextProvider>
          <footer>Test footer</footer>
        </UidContextProvider>
      </body>
    </html>
  );
}
